### ISSUE TITLE
Undefined class 'SourceItemsSaveInterface' 

### ISSUE THREAD

**Issue by hans2103** [hans2103/B2bzanden_M2_AlwaysShip#1]
Doordat deze class `SourceItemsSaveInterface` niet gevonden wordt in Magento 2.4.2 faalt AlwaysShip
https://github.com/B2bZanden/B2bzanden_M2_AlwaysShip/blob/3cd8fee8cea1e375a8389f8dab6cfba692946447/Observer/AlwaysShipOrder.php#L27

zie https://devdocs.magento.com/guides/v2.4/inventory/inventory-api-reference.html#inventory-management-api

Graag de module aanpassen, zodat AlwaysShip weer werkt

**Comment by SolsWebdesign** [comment]
het bleek dat er gebruik gemaakt was van yireo / magento2-replace-inventory waardoor alle inventory modules misten. De oude methode gaan ze vanaf... 2.4.3? verwijderen. In ieder geval is het al niet geadviseerd om msi (multi stock inventory) te verwijderen vanaf 2.4.1 en deze zat er ook al in. Het is dus voldoende om de inventory modules terug te zetten.

**Comment by SolsWebdesign** [comment]
Hans, kun jij ze terug zetten?

**Comment by hans2103** [comment]
@SolsWebdesign de inventory modules staan inmiddels terug.

**Comment by hans2103** [comment]
issue is reeds verholpen volgens @jef8 
https://github.com/B2bZanden/OnderdelenExpertM2/issues/279#issuecomment-915145332
